version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000 #local_host:docker_host
    volumes:
      - .:/djangoapp # . means current location file, /djangoapp means docker container update location
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_NATIVE_PASSWORD: admin
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306 #if you use same port it will conflict of mysql installation.